### PR TITLE
New Search Bar + Fly To works

### PR DESCRIPTION
**Pull request by CelineMP**
New expandable Search Bar on top left on map.
Favorites always fixed on top.
All results can be added to favorites now.

In MapOptions I kept the old button that triggers the SearchPopUp in comments so we can quickly change if we prefer the old design.

I didn't integrate the latitude-longitude search as I want to discuss it first. My opinion is to leave it like that because users copy paste coordinates anyway and don't need a seperate input mode.

I was not sure about the folder structure. SearchBar.tsx is now in the PopUp folder, has to be changed eventually.

### CODE REVIEW

**Review by Lucas-Nan — DISMISSED** [review]
looks good enough for release. small things like corners can be changed later. FlyTo is doing (random) stuff. still todo for later

**Review by Lucas-Nan — DISMISSED** [review]
looks good enough for release. small things like corners can be changed later. FlyTo is doing (random) stuff - still todo for later

**Comment by CelineMP** [comment]
Added some commits that make flying to a location from the search possible now

**Review by Lucas-Nan — APPROVED** [review]
looks good enough for release. small things like corners can be changed later. I really like the flyTo

**Pull request merged**
