### PR TITLE
Issue#309 table agnostic api

### PR DESCRIPTION
**Pull request by Superschnizel**
This is only an initial "part 1" PR, since some of the functionality is not fully implemented yet but there are some significant changes so i wanted to already make a PR because there are already a lot of changes.

This PR concerns #309 and solves #335 .

- Created Metadata Library Project.
  - had to change the Docker Compose and Dockerfiles to import the library in all projects where it is used.
- Created a ShapeDatasetHandler that handles dealing with the different tables.
- Extended the Datapipeline to also save the Bounding Box.
- Fixed a Bug where lat and lon were switched.
- various refactorings and code improvements.

### CODE REVIEW

**Review by Lucas-Nan — CHANGES_REQUESTED** [review]
doesnt work for house footprints in docker. maybe the long/latt switch is not completely working. Please check if it works for you. heres the bug by the way for the long latt: https://github.com/amosproj/amos2024ss04-building-information-enhancer/issues/340

**Comment by Superschnizel** [comment]
> doesnt work for house footprints in docker. maybe the long/latt switch is not completely working. Please check if it works for you. heres the bug by the way for the long latt: #340

What exactly is the issue with the house footprints in docker?

**Comment by Lucas-Nan** [comment]
> > doesnt work for house footprints in docker. maybe the long/latt switch is not completely working. Please check if it works for you. heres the bug by the way for the long latt: #340
> 
> What exactly is the issue with the house footprints in docker?

not visible in FE. Timeout for query: "
SqlException: Execution Timeout Expired. The timeout period elapsed prior to completion of the operation or the server is not responding. A transport-level error has occurred when receiving results from the server. (provider: TCP Provider, error: 35 - An internal exception was caught)

    Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, bool breakConnection, Action<Action> wrapCloseInAction)
    Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, bool breakConnection, Action<Action> wrapCloseInAction)
    Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, bool callerHasConnectionLock, bool asyncClose)
    Microsoft.Data.SqlClient.TdsParserStateObject.SNIWritePacket(PacketHandle packet, out uint sniError, bool canAccumulate, bool callerHasConnectionLock)
    Microsoft.Data.SqlClient.TdsParserStateObject.SendAttention(bool mustTakeWriteLock)
    Microsoft.Data.SqlClient.TdsParserStateObject.ReadSniError(TdsParserStateObject stateObj, uint error)
    Microsoft.Data.SqlClient.TdsParserStateObject.ReadSniSyncOverAsync()
    Microsoft.Data.SqlClient.TdsParserStateObject.TryReadNetworkPacket()
    Microsoft.Data.SqlClient.TdsParserStateObject.TryPrepareBuffer()
    Microsoft.Data.SqlClient.TdsParserStateObject.TryReadByteArray(Span<byte> buff, int len, out int totalRead)
    Microsoft.Data.SqlClient.TdsParserStateObject.TryReadChar(out char value)
    Microsoft.Data.SqlClient.TdsParser.TryReadPlpUnicodeCharsChunk(char[] buff, int offst, int len, TdsParserStateObject stateObj, out int charsRead)
    Microsoft.Data.SqlClient.TdsParser.TryReadPlpUnicodeChars(ref char[] buff, int offst, int len, TdsParserStateObject stateObj, out int totalCharsRead)
    Microsoft.Data.SqlClient.TdsParser.TryReadSqlStringValue(SqlBuffer value, byte type, int length, Encoding encoding, bool isPlp, TdsParserStateObject stateObj)
    Microsoft.Data.SqlClient.TdsParser.TryReadSqlValue(SqlBuffer value, SqlMetaDataPriv md, int length, TdsParserStateObject stateObj, SqlCommandColumnEncryptionSetting columnEncryptionOverride, string columnName, SqlCommand command)
    Microsoft.Data.SqlClient.SqlDataReader.TryReadColumnInternal(int i, bool readHeaderOnly)
    Microsoft.Data.SqlClient.SqlDataReader.GetValueInternal(int i)
    Microsoft.Data.SqlClient.SqlDataReader.GetValue(int i)
    BIE.Core.DBRepository.DbHelper.GetData(string sqlQuery)+MoveNext() in DBHelper.cs
    BIE.Core.API.Controllers.DatasetController.GetHouseFootprintsData(QueryParameters parameters) in DatasetController.cs
    BIE.Core.API.Controllers.DatasetController.GetDatasetViewportData(QueryParameters parameters) in DatasetController.cs
    lambda_method4(Closure , object , object[] )
    Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor+SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, object controller, object[] arguments)
    Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
    Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
    Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
    Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
    Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
    Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
    Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
    Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
    Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
    Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
    Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
    Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
    Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
    Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

"

with the following request: "http://localhost:8082/api/v1.0/Dataset/getDatasetViewportData?Id=house_footprints&ZoomLevel=8&BottomLat=48.297802&BottomLong=10.353156&TopLat=50.387497&TopLong=13.967658"

**Comment by Lucas-Nan** [comment]
sorry dont have a lot of time this weekend. can check tomorrow morning

**Comment by Superschnizel** [comment]
@Lucas-Nan did you run it with `npm run deploy` or `npm run deploy:build` because it seems that the stacktrace shows functions that are no longer being used, so if you were using just `deploy` the images were not being rebuilt.

**Comment by Superschnizel** [comment]
I found some issues related to a missing ENV variable as well as one where the coordinates were sent as string instead of float. This issue still persists in house footprints and actual use. i will fix it tomorrow.

**Review by Lucas-Nan — CHANGES_REQUESTED** [review]
i completely cleaned docker (including the volume) and got this error in the pipeline: "Starting the Data Pipeline for ./yaml/development/hausumringe_mittelfranken_small.yaml:
2024-07-01 08:19:03 type:       filepath
2024-07-01 08:19:03 format:     SHAPE
2024-07-01 08:19:03 location:   ./yaml-data/hausumringe_mittelfranken_small.zip
2024-07-01 08:19:03 table name: Hausumringe_mittelfranken_small
2024-07-01 08:19:03 
2024-07-01 08:19:03 Established the database connection.
2024-07-01 08:19:03 Starting the importer...
2024-07-01 08:19:03 Opening local Zip file ./yaml-data/hausumringe_mittelfranken_small.zip
2024-07-01 08:19:03 Error while setting up the importer.
2024-07-01 08:19:03 System.IO.DirectoryNotFoundException: Could not find a part of the path '/app/yaml-data/hausumringe_mittelfranken_small.zip'.
2024-07-01 08:19:03    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
2024-07-01 08:19:03    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
2024-07-01 08:19:03    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
2024-07-01 08:19:03    at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
2024-07-01 08:19:03    at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
2024-07-01 08:19:03    at System.IO.FileStream..ctor(String path, FileMode mode)
2024-07-01 08:19:03    at BIE.DataPipeline.Import.ShapeImporter.SetupParser() in /app/src/BIE.DataPipeline/Import/ShapeImporter.cs:line 55
2024-07-01 08:19:03    at BIE.DataPipeline.Import.ShapeImporter..ctor(DataSourceDescription dataSourceDescription) in /app/src/BIE.DataPipeline/Import/ShapeImporter.cs:line 26
2024-07-01 08:19:03    at Program.<Main>$(String[] args) in /app/src/BIE.DataPipeline/Program.cs:line 75"

maybe the zip file is not copied correctly anymore

**Comment by Superschnizel** [comment]
Okay, i finally managed to get it to a real working state:

- added the missing .zip to the projects copy-always
- found out that the frontend expects a triple nested float array as coordinates (are we maybe changing some of the data here?)

@Lucas-Nan @Corgam please check the PR again, should all work now

**Review by Lucas-Nan — APPROVED** [review]
great refactorings and bug fixes!

**Pull request merged**
