### PR TITLE
Display polygon for specific region

### PR DESCRIPTION
**Pull request by CelineMP**
I completed this task https://github.com/amosproj/amos2024ss04-building-information-enhancer/issues/195

Bildschirmfoto 2024-06-11 um 19 30 27

If you move the marker or change the search input, the polygon is removed.

### CODE REVIEW

**Comment by Lucas-Nan** [comment]
well i have to say that this ticket is very misleading. In the discussion the result was more that INSTEAD of the red marker you have a marked region. And then a request will of course request data for this area and not just for a single point. I am admittedly a bit unsure how to proceed. I would still accept it as it is a nice feature anyways but maybe not the intended version

**Review by Corgam — CHANGES_REQUESTED** [review]
Looks really good! Just one thing, after searching a place and moving the map the polygon disappears, it would be nice to keep the search after moving the map, so the text and the polygon stays rendered. Additionally, as discussed, it would be nice to have a `Go to` button at the end of the search bar to once again search for the currently written address and a clear text button before that

**Comment by CelineMP** [comment]
@Lucas-Nan @Corgam 

I implemented your feedback now :) No more markers inside polygons and the polygon doesn't vanish when moving the map

> Additionally, as discussed, it would be nice to have a Go to button at the end of the search bar to once again search for the currently written address and a clear text button before that.

There is a different ticket for it :)

**Review by Corgam — APPROVED** [review]
The selection of a polygon on search is finished, the other tasks will be done as a separate PR (discussed with FE team).

**Pull request merged**
