### PR TITLE
Added endpoint for clustered data

### PR DESCRIPTION
**Pull request by Ahsankkhan**
Added endpoint for clustered data 
#240

### CODE REVIEW

**Review by Lucas-Nan — COMMENTED** [review]
error encountered with http://localhost:8081/api/v1.0/Dataset/2/clustereddata?BottomLat=49.568&BottomLong=11.003&TopLat=49.5820&TopLong=11.0613&ZoomLevel=100.0 currently checking

**Review by Lucas-Nan — CHANGES_REQUESTED** [review]
fix error on empty set of points http://localhost:8081/api/v1.0/Dataset/2/clustereddata?BottomLat=49&BottomLong=11&TopLat=49&TopLong=11&ZoomLevel=100

**Comment by Ahsankkhan** [comment]
> http://localhost:8081/api/v1.0/Dataset/2/clustereddata?BottomLat=49&BottomLong=11&TopLat=49&TopLong=11&ZoomLevel=100

Fixed now

**Review by Lucas-Nan — APPROVED** [review]
both empty results and clustered results seem to work! (and without cluster as well)

**Pull request merged**
